"""empty message

Revision ID: 4bf17816a494
Revises: a4863a425ac5
Create Date: 2018-12-28 17:23:12.097845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bf17816a494'
down_revision = 'a4863a425ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('permissions', sa.Integer(), nullable=True))
    op.drop_column('cms_role', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('permission', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('cms_role', 'permissions')
    # ### end Alembic commands ###
